[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все ui автотесты
    smoke: Маркировка для смоук тестов
    regression: Маркировка для регрессионых тестов
    registration: Маркировка для тестов регистрации
    slow: Маркировка для медленных тестов
    critical: Маркировка для медленных тестов
    authorization: Маркировка для тестов авторизации
    courses: Маркировка для тестов курсов